GROUP=org.multi-os-engine
POM_ARTIFACT_ID=javapymobiledevice3
VERSION=1.2.0

POM_NAME=JavaPyMobiledevice3
POM_DESCRIPTION=An IPC bridge between java and pymobiledevice3
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/multi-os-engine/JavaPyMobiledevice3/

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/multi-os-engine/JavaPyMobiledevice3/
POM_SCM_CONNECTION=scm:git:git://github.com/multi-os-engine/JavaPyMobiledevice3.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/multi-os-engine/JavaPyMobiledevice3.git

POM_DEVELOPER_ID=MOE
POM_DEVELOPER_NAME=Multi-OS Engine Dev
POM_DEVELOPER_URL=https://www.multi-os-engine.org/
